TRAIN:
  USE_CUDA: True
  MAX_EPOCH: 60
  BATCH_SIZE: 8
  LR: 0.0001
  DROPOUT: 0.0
  SEED: 1234

  SAVE_PATH: 'train_logs/diving_logs/CPA_learnStep'

MODEL:
  BACKBONE: 'cat'
  BASE_MODEL: 'resnet50'
  PRETRAIN: 'pretrained_models/resnet50-kinetics400.pth'
  DIM_EMBEDDING: 128
  TRANSFORMER: False
  ALIGNMENT: False
  SAVE_EPOCHS: 1

DATASET:
  MODE: 'train'

# #  CSV dataset
  # NAME: 'CSV'
  # ROOT: './Datasets/CSV/video_compressed'
  # TXT_PATH: './Datasets/CSV/train_pairs.txt'
  # NUM_CLASS: 45
  # LOAD_VIDEO: True

#  COIN dataset
  # NAME: 'COIN-SV'
  # ROOT: 'Datasets/COIN-SV/video_compressed'
  # TXT_PATH: './Datasets/COIN-SV/train_pairs.txt'
  # NUM_CLASS: 37
  # LOAD_VIDEO: True


#  Diving dataset
  NAME: 'DIVING48-SV'
  ROOT: './Datasets/DIVING48-SV/video_compressed'
  TXT_PATH: './Datasets/DIVING48-SV/train_neg_pairs.txt'
  NUM_CLASS: 20
  LOAD_VIDEO: True


  NUM_SAMPLE: 3200
  NUM_CLIP: 16
  AUGMENT: True
  SHUFFLE: True
  NUM_WORKERS: 8
