TRAIN:
  BATCH_SIZE: 1
  DROPOUT: 0.0


MODEL:
  DIM_EMBEDDING: 128
  ITERS: 4
  TRANSFORMER: False
  ALIGNMENT: False


DATASET:
  MODE: 'test'
  LOAD_VIDEO: False

#  CSV dataset
  NAME: 'CSV'
  ROOT: 'vis_results'
  TXT_PATH: './Datasets/CSV/vis_pairs.txt'
  NUM_CLASS: 45

#  COIN dataset
  # NAME: 'COIN-SV'
  # # TXT_PATH: './Datasets/COIN-SV/val_pairs.txt'
  # ROOT: 'Datasets/COIN-SV/video_compressed'
  # TXT_PATH: './Datasets/COIN-SV/test_pairs.txt'
  # NUM_CLASS: 37

#  Diving48 dataset;
  # NAME: 'DIVING48-SV'
  # ROOT: 'Datasets/DIVING48-SV/video_compressed'
  # # TXT_PATH: '/Datasets/DIVING48-SV/val_pairs.txt'
  # TXT_PATH: './Datasets/DIVING48-SV/test_pairs.txt'
  # NUM_CLASS: 20


  NUM_CLIP: 16
  AUGMENT: False
  SHUFFLE: True
  NUM_WORKERS: 1


